# 对比学习训练配置文件

# 数据配置
data:
  # 数据列配置
  input_columns: ["CIR"]        # 输入列名列表，支持多列
  target_column: "TOA"          # 目标列名（用于微调阶段）
  keep_columns: ["tx_signal_file"] # 保存到预测结果中的原始列
  
  # 序列处理配置
  sequence_length: null         # 序列长度，null表示自动确定
  max_sequence_length: 2000     # 最大序列长度限制
  
  # 标准化配置
  normalize_features: true      # 是否标准化特征
  normalize_targets: true       # 是否标准化目标（微调时使用）
  scaler_type: "minmax"         # 标准化类型: standard, minmax
  
  # 数据划分配置
  train_ratio: 0.8             # 训练集比例
  val_ratio: 0.1               # 验证集比例
  test_ratio: 0.1              # 测试集比例

# 模型配置
model:
  type: "lstm"                 # 基础模型类型: lstm, transformer
  hidden_size: 128              # 隐藏层大小
  num_layers: 8                # 层数
  dropout: 0.1                 # Dropout率
  bidirectional: true          # LSTM是否双向
  # Transformer专用参数
  nhead: 8                     # 注意力头数

# 对比学习配置
contrastive:
  # 预训练阶段
  pretrain_epochs: 50          # 对比学习预训练轮数
  temperature: 1.0             # 对比学习温度参数
  projection_dim: 128          # 投影头输出维度
  projection_hidden_dim: 256   # 投影头隐藏层维度
  
  # 数据增强配置
  augmentation:
    noise_std: 0.01            # 高斯噪声标准差
    dropout_rate: 0.1          # 随机dropout比率
    time_shift_ratio: 0.1      # 时间偏移比率
  
  # 训练配置
  learning_rate: 0.01          # 预训练学习率
  weight_decay: 1e-5           # 权重衰减
  batch_size: 128              # 批次大小
  
  # 学习率调度器
  scheduler:
    type: "cosine"             # 调度器类型: cosine, step
    step_size: 30              # StepLR的步长
    gamma: 0.5                 # 衰减因子

# 微调配置
finetune:
  epochs: 30                   # 微调训练轮数
  learning_rate: 0.0001        # 微调学习率
  weight_decay: 1e-5           # 权重衰减
  batch_size: 32               # 批次大小
  freeze_backbone: false       # 是否冻结backbone
  
  # 损失函数配置
  loss_function:
    type: "auto"               # 损失函数类型: auto, mse, mae, huber
  
  # 学习率调度器
  scheduler:
    type: "plateau"            # 调度器类型: plateau, step, cosine
    patience: 5                # ReduceLROnPlateau的耐心值
    factor: 0.5                # 衰减因子
  
  # 早停配置
  early_stopping:
    patience: 10               # 早停耐心值
    min_delta: 1e-4            # 最小改善值

# 训练模式配置
training_mode: "contrastive"   # 训练模式: supervised, contrastive, both

# 设备配置
device: "auto"                 # 设备选择: auto, cpu, cuda, mps

# 随机种子
seed: 42

# 日志配置
logging:
  level: "INFO"
  save_dir: "logs"
  tensorboard: true
