# 统一训练配置文件 - 支持自动数据类型检测

# 数据配置
data:
  # 数据列配置
  input_columns: ["CIR"]        # 输入列名列表，支持多列
  target_column: "TOA"          # 目标列名
  
  # 序列处理配置
  sequence_length: null         # 序列长度，null表示自动确定
  max_sequence_length: 2000     # 最大序列长度限制
  
  # 标准化配置
  normalize_features: true      # 是否标准化特征
  normalize_targets: true       # 是否标准化目标
  scaler_type: "minmax"         # 标准化类型: standard, minmax
  
  # 数据划分配置
  train_ratio: 0.8             # 训练集比例
  val_ratio: 0.1               # 验证集比例
  test_ratio: 0.1              # 测试集比例

# 模型配置
model:
  type: "transformer"                # 模型类型: lstm, transformer
  hidden_size: 128                   # 隐藏层大小
  num_layers: 2                      # 层数
  dropout: 0.2                       # Dropout率
  bidirectional: False               # LSTM是否双向
  # Transformer专用参数
  nhead: 8                           # 注意力头数

# 训练配置
training:
  epochs: 100                # 训练轮数
  batch_size: 32             # 批次大小
  learning_rate: 0.001       # 学习率
  weight_decay: 1e-5         # 权重衰减
  
  # 损失函数配置
  loss_function:
    type: "auto"             # 损失函数类型: auto, mse, mae, huber, smooth_l1, crossentropy, bce
    
  # 优化器配置
  optimizer:
    type: "adam"             # 优化器类型: adam, sgd
    beta1: 0.9
    beta2: 0.999
    eps: 1e-8
  
  # 学习率调度器
  scheduler:
    type: "cosine"           # 调度器类型: step, cosine, plateau
    step_size: 30            # StepLR的步长
    gamma: 0.1               # 衰减因子
    patience: 10             # ReduceLROnPlateau的耐心值
  
  # 早停配置
  early_stopping:
    patience: 15             # 早停耐心值
    min_delta: 1e-4          # 最小改善值
    mode: "min"              # 监控模式: min, max
    monitor: "val_loss"      # 监控指标

# 设备配置
device: "auto"               # 设备选择: auto, cpu, cuda, mps

# 随机种子
seed: 42

# 日志配置
logging:
  level: "INFO"
  save_dir: "logs"
  tensorboard: true
